print("How old are you?", end=" ")
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weight?", end=' ')
weight = input()
print(f"so, you are {age} old, {height} tall, {weight} heavy")